social_copy1/groups/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views


app_name = 'groups'

urlpatterns = [
    url(r'^create/$', views.CreateGroup, name='create_group'),
    url(r'^group_list/$', views.GroupList, name='group_list'),
    url(r'^(?P<slug>[-\w]+)/$', views.GroupSingle, name='group_single'),
    url(r'^join/(?P<slug>[-\w]+)/$', views.GroupJoin, name='group_join'),
    url(r'^leave/(?P<slug>[-\w]+)/$', views.GroupLeave, name='group_leave')

]

social_copy1/posts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views


app_name = 'posts'

urlpatterns = [
    url(r'^create/(?P<slug>[-\w]+)/$', views.PostCreate, name='post_create'),
    url(r'^delete/(?P<slug>[-\w]+)/(?P<pk>[0-9]+)/$', views.PostDelete, name='post_delete'),
    url(r'^by/(?P<username>[-\w]+)/$', views.UserPostDetail, name='user_post'),

]

social_copy1/social_copy1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.Index.as_view(), name='index'),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^test/', views.TestPage.as_view(), name='test'),
    url(r'^thanks/', views.ThanksPage.as_view(), name='thanks'),
    url(r'^groups/', include('groups.urls')),
     url(r'^posts/', include('posts.urls')),



]

social_copy1/groups/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
# Create your models here.

import misaka


from django import template


class Group(models.Model):
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(default='')
    description_html = models.TextField(blank=True, default='')
    member = models.ManyToManyField(User, blank=True, through='GroupMember')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ['group', 'user']

social_copy1/groups/forms.py
from django import forms
from .models import Group, GroupMember


class GroupCreateForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name', 'description', )

social_copy1/groups/views.py
from django.shortcuts import render
from .models import Group, GroupMember
from django.utils.text import slugify
from .forms import GroupCreateForm
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
import misaka
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required


def CreateGroup(request):
    if request.method == 'POST':
        create_form = GroupCreateForm(request.POST)
        if create_form.is_valid:
            group_form = create_form.save(commit=False)
            group_form.slug = slugify(group_form.name)
            group_form.description_html = misaka.html(group_form.description)
            # group_form.members.add(request.user)
            group_form.save()

            return HttpResponseRedirect(reverse('index'))
        else:
            print(create_form.errors)
    else:
        create_form = GroupCreateForm()
    return render(request, 'groups/group_create.html',
                  {'create_form': create_form})


def GroupList(request):
    group_list = Group.objects.all()
    return render(request, 'groups/group_list.html',
                  {'group_list': group_list})


def GroupSingle(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'groups/group_single.html', {'group': group})

@login_required
def GroupJoin(request, slug):
    group_name = get_object_or_404(Group, slug=slug)
    group = GroupMember(group=group_name, user=request.user)
    group_name.member.add(group.user)
    return HttpResponseRedirect(reverse('groups:group_single', kwargs={'slug':slug}))

@login_required
def GroupLeave(request, slug):
    group_name = get_object_or_404(Group, slug=slug)
    group_mem = get_object_or_404(GroupMember, group=group_name, user=request.user)
    group_name.member.remove(group_mem.user)
    group_mem.delete()
    return HttpResponseRedirect(reverse('groups:group_single', kwargs={'slug': slug}))

social_copy1/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

social_copy1/groups/templates/groups/group_create.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST"  id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form create_form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

social_copy1/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:user_post' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create_group' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in group_list %}
		  <a class="list-group-item" href="{% url 'groups:group_single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.member.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

social_copy1/groups/templates/groups/group_single.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
    <h2>{{ group.name }}</h2>
    <p>Member Count : {{ group.member.count }}</p>

    {% if user.is_authenticated %}
        {% if user in group.member.all %}
            <a href="{% url 'groups:group_leave' slug=group.slug %}" class="btn btn-lg btn-danger"><span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
             <a href="{% url 'posts:post_create' slug=group.slug %}" class="btn btn-lg btn-success"><span class="glyphicon glyphicon-plus-sign"></span>Create Post</a>
        {% else %}
            <a href="{% url 'groups:group_join' slug=group.slug %}" class=" btn btn-lg btn-warning "><span class="glyphicon glyphicon-ok-circle"></span>Join</a>
        {% endif %}
    {% endif %}


{% endblock %}


{% block group_content %}
    <div class="col-md-8">
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}