Online_School/Online_School/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from . import views
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$', views.Homepage.as_view(), name='homepage'),
    url(r'^accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    url(r'^subject/', include('subject.urls')),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Online_School/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^student_sign_up/$', views.StudentSignUp, name='student_sign_up'),
    url(r'^teacher_sign_up/$', views.TeacherSignUp, name='teacher_sign_up'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', views.UserLogin, name='login'),
    url(r'^(?P<username>[-\w]+)/$', views.ProfileSingle, name='profile_single'),
]

Online_School/subject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from . import views
from django.conf.urls.static import static

app_name = 'subject'
urlpatterns = [
    url(r'^course_list/$', views.CourseList, name='course_list'),
    url(r'^create/$', views.CourseCreate, name='course_create'),
    url(r'^(?P<slug>[-\w]+)/$', views.CourseDetail, name='course_detail'),
    url(r'^(?P<slug>[-\w]+)/join/$', views.CourseJoin, name='course_join'),
    url(r'^(?P<slug>[-\w]+)/leave/$', views.CourseLeave, name='course_leave'),
]

Online_School/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% block css_content %}
    
    {% endblock %}
    <title></title>
</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-light ">
        {% if user.is_authenticated %}
            <a class="navbar-brand" href="{% url 'accounts:profile_single' username=user.username %}"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTV2sYW0D0CdvFM08YhbtLv6eEoKD0f3YTc3KnlHarmuBi4Ri5U" width="30" height="30" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% else %}
            <a class="navbar-brand" href="{% url 'homepage' %}"><img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTV2sYW0D0CdvFM08YhbtLv6eEoKD0f3YTc3KnlHarmuBi4Ri5U" width="30" height="30" alt=""></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% endif %}

        <div id="navbarNavDropdown" class="navbar-collapse collapse">
            <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                   <li class="nav-item">
                      <a href="#" color="white">Hi, {{ user.first_name | title }}</a>
                   </li>
                {% else %}
                {% endif %}
            </ul>
            <ul class="navbar-nav">
                {% if user.is_superuser %}
                    <li class="nav-item">
                      <a class="btn btn-primary" href="{% url 'subject:course_create' %}" color="white">Add course</a>
                   </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                      <a class="btn btn-primary" href="{% url 'subject:course_list' %}" color="white">Courses</a>
                   </li>
                    <li class="nav-item">
                      <a class="btn btn-primary" href="{% url 'accounts:logout' %}" color="white">Logout</a>
                   </li>
                {% else %}
                    <li class="nav-item">
                      <a class="btn btn-primary" href="{% url 'accounts:login' %}" color="white">Login</a>
                   </li>
                {% endif %}
                {% if user.is_authenticated or user.is_superuser %}
                   {% else %}
                       <li class="nav-item">
                       <a class="btn btn-primary" href="{% url 'accounts:teacher_sign_up' %}" color="white">Teacher SignUp</a>
                    </li>
                   <li class="nav-item">
                      <a class="btn btn-primary" href="{% url 'accounts:student_sign_up' %}" color="white">Student SignUp</a>
                   </li>
                {% endif %}
                <li class="nav-item">
                    <a class="btn btn-primary" href="#" color="white">About Us</a>
                </li>
            </ul>
        </div>
    </nav>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

Online_School/templates/homepage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block css_content %}
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <h2>Welcome to the classroom Web app.<br></h2>
        <div class="container" align="center">
            <img src="https://www.eschoolpad.com/wp-content/uploads/2015/09/g_apple_classroom.png" width="600" height="400" alt="">
            <h3>To get started create an account.</h3>
        </div>
    </div>
{% endblock %}