first_project/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from blog import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
    url(r'^post/(?P<pk>\d+)$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name='post_update'),
    url(r'^post/(?P<pk>\d+)/delete/$', views.PostDeleteView.as_view(), name='post_delete'),
    url(r'^draft/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.contrib.auth import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'})

]

first_project/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now())
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        reverse('post_list')

    def __str__(self):
        return self.text

first_project/blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = ('author', 'title', 'text')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea postcontent'})
        }


class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = ('author', 'text')

        widgets ={
            'author': forms.TextInput(attrs={'class': 'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'})
        }

first_project/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import PostForm, CommentForm
from . import models
from django.urls import reverse_lazy
# Create your views here.


class AboutView(TemplateView):
    template_name = 'blog/about.html'


class PostListView(ListView):
    model = models.Post

    def get_queryset(self):
        return models.Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = models.Post


class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = models.Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = models.Post


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = models.Post
    success_url = reverse_lazy('post_list')


class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'

    def get_queryset(self):
        return models.Post.objects.filter(published_date__isnull=True).order_by('-create_date')


###################################################
###################################################


@login_required
def post_publish(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=post.pk)

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(models.Post, pk=pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = CommentForm()
        return render(request, 'blog/comment_form.html', {'form': form})



@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

first_project/blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>About this Company</h1>
    <p>Thanks for visiting.</p>

{% endblock %}

first_project/blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
     {#    Bootstrap#}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">

    <link rel="stylesheet" href="{% static 'CSS/blog.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Domine|Roboto&display=swap" rel="stylesheet">

</head>
<body class="loader">
    <nav class="navbar navbar-default techfont custom-navbar">
        <div class="container">
           <ul class="nav navbar-nav">
                <li><a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">My blog</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
            <li><a href="https://www.github.com">GitHub</a></li>
            <li><a href="https://www.linkedin.com">LinkedIn</a></li>
           </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                    <a href="{% url 'blog:post_new' %}">New Post</a>
                    </li>
                    <li>
                    <a href="{% url 'blog:post_draft_list' %}">Drafts</a>
                    </li>
                    <li>
                    <a href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li>
                    <a>Welcome : {{ user.username }}</a>
                    </li>

                    {% else %}
                     <li class="nav navbar-nav navbar-right"><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span></a></li>
                {% endif %}
            </ul>




        </div>
    </nav>
    <div class="content container">
        <div class="row">
            <div class="blog_posts">
                {% block content %}

                {% endblock %}
            </div>
        </div>
    </div>

</body>
</html>

first_project/blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %}
{% block content %}
<h1>New Comment</h1>
    <form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Post Comment</button>
    </form>
    <script>
    var editor = new MediumEditor('.editable');
    </script>
{% endblock %}

first_project/blog/templates/blog/post_conform_delete.html
{% extends 'blog/base.html' %}

{% block content %}
    <form method="post">
    {% csrf_token %}
        <p>Are you sure you want to delete {{ object }} ?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
{% endblock %}

first_project/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1 class="posttitle loader">{{ post.title }}</h1>
    {% if post.published_date %}
        <div class="date postdate">
         {{ post.published_date }}
        </div>
        {% else %}
        <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk%}">Publish</a>
    {% endif %}
    <p class="postcontent">{{ post.title|safe|linebreaksbr}}</p>
    {% if user.is_authrnticated %}
        <a class="btn btn-primary" href="{% url 'blog:post_update'  pk=post.pk %}">
        <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <a class="btn btn-primary" href="{% url 'blog:post_delete'  pk=post.pk %}">
        <span class="glyphicon glyphicon-remove"></span>
        </a>
    {% endif %}
    <hr>
     <a class="btn btn-primary btn-content" href="{% url 'blog:add_comment_post' pk=post.pk%}">Add Comment</a>
    <div class="container">
    {% for comment in post.comments.all %}
        <br>
        {% if user.is_authenticated or comment.approved_comment %}
            {{ comment.created_date }}
            {% if not comment.approved_comment %}

        <a class="btn btn-default" href="{% url 'blog:comment_approve'  pk=comment.pk%}">
        approve
        </a>
                <a class="btn btn-default" href="{% url 'blog:comment_remove'  pk=comment.pk%}">remove

        </a>
            {% endif %}

        <p>{{comment.text|safe|linebreaks}}</p>
            <p>Published by : {{ comment.author }}</p>
        {% endif %}
        {% empty %}
        <p>No Comments</p>
    {% endfor %}

    </div>
{% endblock %}

first_project/blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
        <p class="date">Created: {{ post.created_date|date:'d-m-Y'}}</p>
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <p>{{ post.text|truncatechars:200}}</p>
        </div>
    {% endfor %}

{% endblock %}

first_project/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block content %}
    <h1>New Post</h1>
    <form class="post_form" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default" value="">Save</button>
    </form>
    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

first_project/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="centerstage">
        {% for post in post_list %}
            <div class="post">
             <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <div class="date">
                <p>Published on: {{ post.published|date:"D M Y"}}</p>
            </div>
            <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
            </div>
        {% endfor %}

    </div>
{% endblock %}