CBV/CBV/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.CBView.as_view(), name='CBView'),
    url(r'^basic_app/',include('basic_app.urls')),
]

CBV/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    url(r'^index/', views.CBView.as_view(), name='CBView'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

CBV/basic_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here


class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

CBV/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View,ListView,DetailView,TemplateView,
                                  CreateView,UpdateView,DeleteView)
from django.http import HttpResponse
from . import models
from django.urls import reverse_lazy

class CBView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    template_name = 'basic_app/schoollist.html'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    template_name = 'basic_app/schooldetail.html'
    model = models.School


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list')

CBV/basic_app/templates/basic_app/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href={% url 'basic_app:list' %}>Schools</a></li>
            <li><a class="navbar-brand" href={% url 'admin:index' %}>Admin</a></li>
            <li><a href={% url 'basic_app:CBView' %}>Homepage</a></li>
        </ul>
    </nav>

 <div class="container">
     {% block body_block %}

     {% endblock %}
 </div>

</body>
</html>

CBV/basic_app/templates/basic_app/department_detail.html
{% extends  %}

CBV/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic.html' %}
{% block body_block %}
    <h1>Delete {{ school.name }} ?</h1>
    <form method="post">
    {% csrf_token %}
    <input type="submit" class = 'btn btn-dnager' value="delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
    </form>
{% endblock %}

CBV/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic.html' %}
{% block body_block %}
    <h1>
        {% if not form.instance.pk %}
            Create School
        {% else %}
            Update School
        {% endif %}
    </h1>
    <form method="post">
    {% csrf_token %}
      {{ form.as_p }}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

{% endblock %}

CBV/basic_app/templates/basic_app/schooldetail.html
{% extends 'basic_app/basic.html' %}

{% block body_block %}
    <div class="jumbotron">
    <h1>Welcome to school detail page</h1>
    <h2>School details</h2>
    <p>Name: {{ school_detail.name }}</p>
    <p>Principal: {{ school_detail.principal }}</p>
    <h3>Students</h3>
    <ol>
        {% for student in school_detail.students.all %}
            <p>{{ student.name }} who is {{ student.age }} years old.</p>
        {% endfor %}
    </ol>
    </div>
    <div class="container">
        <p><a class='btn btn-warning' href="{% url 'basic_app:update'  pk=school_detail.pk %}">Update</a></p>
        <p><a class='btn btn-danger' href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
    </div>


{% endblock %}

CBV/basic_app/templates/basic_app/schoollist.html
{% extends 'basic_app/basic.html' %}


{% block body_block %}
    <h1>Welcome to list of school</h1>
    <ol>
      {% for school in schools %}
          <h2><li><a href= "{{ school.id }}">{{ school.name }}</a></li></h2>
    {% endfor %}
    </ol>

{% endblock %}

CBV/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href={% url 'basic_app:list' %}>Schools</a></li>
            <li><a class="navbar-brand" href={% url 'admin:index' %}>Admin</a></li>
        </ul>
    </nav>

 <div class="container">
     {% block body_block %}

     {% endblock %}
 </div>

</body>
</html>

CBV/templates/index.html
{% extends 'base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>
        <a class="btn btn-primary" href="{% url 'basic_app:create'%}">create</a>
    </div>
{% endblock %}